import { Room } from "./types/Building";

export const dummyRooms: Room[] = [
	{
		rooms_fullname: "Hugh Dempster Pavilion",
		rooms_shortname: "DMP",
		rooms_number: "110",
		rooms_name: "DMP_110",
		rooms_address: "6245 Agronomy Rd",
		rooms_lat: 49.26125,
		rooms_lon: -123.24807,
		rooms_seats: 120,
		rooms_furniture: "Fixed Tables/Fixed Chairs",
		rooms_type: "Tiered Large Group",
		rooms_href: "#",
    },
	{
		rooms_fullname: "Henry Angus Building",
		rooms_shortname: "ANGU",
		rooms_number: "098",
		rooms_name: "ANGU_098",
		rooms_address: "2053 Main Mall",
		rooms_lat: 49.2661,
		rooms_lon: -123.2548,
		rooms_seats: 60,
		rooms_furniture: "Moveable Tables & Chairs",
		rooms_type: "Small Group",
		rooms_href: "#",
    },
	{
		rooms_fullname: "Buchanan Building",
		rooms_shortname: "BUCH",
		rooms_number: "A202",
		rooms_name: "BUCH_A202",
		rooms_address: "1866 Main Mall",
		rooms_lat: 49.2683,
		rooms_lon: -123.2536,
		rooms_seats: 150,
		rooms_furniture: "Fixed Tables/Fixed Chairs",
		rooms_type: "Tiered Large Group",
		rooms_href: "#",
    },
	{
		rooms_fullname: "Irving K. Barber Learning Centre",
		rooms_shortname: "IKB",
		rooms_number: "185",
		rooms_name: "IKB_185",
		rooms_address: "1961 East Mall",
		rooms_lat: 49.2672,
		rooms_lon: -123.2524,
		rooms_seats: 75,
		rooms_furniture: "Moveable Tables & Chairs",
		rooms_type: "Flat Medium Group",
		rooms_href: "#",
	}
];
